### PR TITLE
Made connection method configurable

### PR DESCRIPTION
**Pull request by rwillard**
Additionally in config, you can specify how you want it to output, defaults to current output. Added ability to see instance name.

### CODE REVIEW

**Comment by buger** [comment]
Are you sure this should be configurable? From what i understand VPC instances just did not have public DNS records, we can detect them, and always use private IP instead of public.

**Comment by buger** [comment]
Also linking this issue https://github.com/buger/cloud-ssh/issues/7

**Comment by Zeelot** [comment]
VPC instances can have both private and public DNS records. This should be configurable because, even if I use a VPC, I might be running `cloud-ssh` from a machine that does not have access to the VPC instances over the private network (for example, if I don't have a VPN configured yet).

**Comment by buger** [comment]
I see, is there is difference then between public_ip and public_dns options?

**Comment by burdandrei** [comment]
:+1: Great one, wanted to do the same, cause all my instances are in VPC, and i got only one gateway configured in my .ssh/config

**Comment by Zeelot** [comment]
I'm not quite sure if there is a case where the public dns might not resolve on a certain machine. I generally always use the public/private ip to connect and avoid the dns but we figured it would be useful to allow for either one depending on preference.

**Comment by Zeelot** [comment]
Although I do think you can configure the VPC to not issue DNS entries for machines automatically. I could look into this further if you are trying to avoid having all 4 options (public/private ip and public/private dns).

**Comment by Zeelot** [comment]
any way this could make it in? are there other issues with it?

**Comment by buger** [comment]
Sorry for such long response! Thank you! Merged

**Pull request merged**
